inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn
Style/StringLiterals:
  Exclude:
    - "config/**/*"
