inherit_gem:
  rubocop-rootstrap:
    - config/rails_edge.yml
inherit_mode:
  merge:
    - Exclude
AllCops:
  Exclude:
    - db/schema.rb
    - config/initializers/pagy.rb
    - bin/bundle
    - bin/yarn
Style/StringLiterals:
  Exclude:
    - "config/**/*"
Layout/HashAlignment:
  Exclude:
    - "lib/**/*"
Layout/LineLength:
  Exclude:
    - "config/**/*"
    - db/migrate/20210413180512_add_devise_to_users.rb
    - db/migrate/20210414141732_add_devise_token_auth_fields_users.rb
    - db/seeds.rb
Rails/Delegate:
  Exclude:
    - app/controllers/api/concerns/act_as_api_request.rb
Rails/RakeEnvironment:
  Exclude:
    - "lib/**/*"
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - lib/**/*
Style/SymbolArray:
  Exclude:
    - config/**/*