FORMAT: 1A
# Rails API Target

# Group Users [api/v1/users/]

## Sign up User [POST]

+ Request Bad

    + Headers

            Content-Type: application/json

    + Body

            + Attributes(User)
            + password_confirmation: password_dont_match

+ Response 404

    + Body

              {
              "status": "error",
              "errors": {
                "password_confirmation": [
                  "doesn't match Password"
                ],
                "full_messages": [
                  "Password confirmation doesn't match Password"
                ]
              }
            }

+ Request 200

    + Headers

            Content-Type: application/json

    + Body

            + Attributes(User)

+ Response 200

    + Body

            {
              "status": "success"",
              "data": {
                "email":"user@example.com",
                "password":"password",
                "password_confirmation":"password_not_match",
                "gender":"M"
              }
            }

# Group Sessions [api/v1/users/sign_in]

## Sign in User [POST]

+ Request Bad

    + Headers

            Content-Type: application/json

    + Body

            Attributes(User_credentials)
            + password: wrong-password

+ Response 404

    + Body

              {
              "status": "error",
              "errors": {
                "full_messages": [
                  "Invalid login credentials. Please try again."
                ]
              }
            }

+ Request 200

    + Headers

            Content-Type: application/json

    + Body

            + Attributes(User_credentials)

+ Response 200
    + Headers

            Access-Token: valid_token
    + Body

            {
              "data": {
                "email":"user@example.com",
                "password":"password",
                "gender":"M",
                "uid":"user@example.com"
              }
            }

# Group Topics [api/v1/topics/]

## Get Topics [GET]

+ Request Bad

    + Headers

            Content-Type: application/json

    + Body

+ Response 401

+ Request 200

    + Headers

            Content-Type: application/json
            access-token: token
    + Body

              "topics": [
                {
                  "topic": {
                    "id": 1,
                    "name": "topic",
                    "image": "URL"
                  }
                }
              ]
            }

+ Response 200

    + Body

            {
              "status": "success"",
              "data": {
                "email":"user@example.com",
                "password":"password",
                "password_confirmation":"password_not_match",
                "gender":"M"
              }
            }

## Data Structures

### User (object)
+ email: user@example.com (required)
+ password: password (required)
+ password_confirmation: password (required)
+ gender: M (required)

### User_credentials (object)
+ email: user@example.com (required)
+ password: password (required)
